name: hotmesh-temporal-comparison
services:
  postgresql:
    container_name: temporal-postgresql
    image: postgres:15.4
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:1.21.3
    ports:
      - 7233:7233
    volumes:
      - ./examples/temporal/config/dynamicconfig:/etc/temporal/config/dynamicconfig
    labels:
      kompose.volume.type: configMap
    healthcheck:
      test:
        [
          "CMD",
          "tctl",
          "--address",
          "temporal:7233",
          "workflow",
          "list"
        ]
      interval: 1s
      timeout: 5s
      retries: 30

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.21.3
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.22.2
    ports:
      - 8080:8080

  harness:
    platform: linux/amd64
    build:
      context: .
      target: development
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
    develop:
      watch:
      - action: sync
        path: .
        target: /home/node/app
        ignore:
          - node_modules/
    depends_on:
      temporal:
        condition: service_healthy
    command: ["sh", "-c", "npm install && npm run start:all"]

volumes:
  db_data:
    driver: local
